Tello5
arekmula/tello_drawer pull request #6
Opened 2021-05-05 11:42 UTC by Krisisss

now with changed method and note from Tello User Guid

2021-05-05 12:54 UTC, Skwarson96 submitted a review, later dismissed

2021-05-05 14:56 UTC, arekmula commented on src/tello/tello.py
> +        max_speed = 100
This should be defined at the top of the class, before init. And constants should be UPPER_CASE

2021-05-05 14:56 UTC, arekmula commented on src/tello/tello.py
> +    def _check_limits(self, x: int, min_lim: int, max_lim: int) -> int:
This function doesn't have to be part of the class, as it doesn't use any of the class variable

2021-05-05 14:58 UTC, arekmula requested changes
At least move the min_movement, max movement, min_speed and max_speed definitions

2021-05-09 13:26 UTC, arekmula approved these changes

2021-05-09 13:51 UTC, Skwarson96 approved these changes

2021-05-09 14:00 UTC, merged